### PR TITLE
Update boolean_filter : on/off support

### PR DESCRIPTION
**Pull request by voondo**
Sometimes used in other libraries (eg. polymer)

### CODE REVIEW

**Comment by tfausak** [comment]
This looks good, thanks! 

What do you think about this, @AaronLasseigne? I think it's reasonable to support.

**Comment by AaronLasseigne** [comment]
It looks good to me. Should we merge the regexp together? `/\A(?:false|off)\z/`

**Comment by tfausak** [comment]
Yeah, but we can do that after this is merged. We could also include the `0` check in there: `/\A(?:0|false|off)\z/`.

**Comment by tfausak** [comment]
Thanks for the addition, @voondo! I'll release a new version shortly.

On that note, what type of change (major or minor) do you think this is, @AaronLasseigne? I'm leaning toward minor.

Also I combined the regexes in 436245aa182f862bd608bf4eeb2f64645f7c4b47.

**Comment by AaronLasseigne** [comment]
I'd go minor.

**Comment by tfausak** [comment]
Released in [version 3.2.0](https://github.com/orgsync/active_interaction/releases/tag/v3.2.0).

**Comment by voondo** [comment]
thanks guys :+1:

**Pull request merged**
