### PR TITLE
Try to fix the Rubinius build

### LINKED ISSUE #388: Rubinius build fails
The gift that keeps on giving. #17 #190 #202

https://travis-ci.org/orgsync/active_interaction/jobs/167886614

### PR DESCRIPTION
**Pull request by tfausak**
This might fix #388.

### CODE REVIEW

**Comment by tfausak** [comment]
I don't see any `rbx` Rubies for Ubuntu 14.04 on http://rubies.travis-ci.org. There are a lot of `rubinius` Rubies on http://rubies.travis-ci.org/rubinius.

**Comment by tfausak** [comment]
Hm, that didn't work either. According to the logs, that build machine is running Ubuntu 12.04. So it should have `rbx-2`. Furthermore, the build worked fine less than a month ago: https://travis-ci.org/orgsync/active_interaction/jobs/161038175

**Comment by tfausak** [comment]
I give up. What do you want to do about this, @AaronLasseigne?

**Comment by AaronLasseigne** [comment]
I say we drop it. I don't think it's used widely enough to be worth the effort. If we get requests to test against it we can consider adding it back.

**Comment by tfausak** [comment]
Should we continue to officially support it even if we don't test it? 

Actually, I just checked and we don't mention Rubinius (or JRuby) anywhere. I feel better about dropping it from Travis because of that.

**Comment by AaronLasseigne** [comment]
Right, I think we can't officially support it if we don't test it but I think we're in the clear.

**Pull request merged**
