### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by waldyr**

### CODE REVIEW

**Comment by tfausak** [comment]
We have discussed adding a code of conduct before. At the time (https://github.com/orgsync/active_interaction/issues/292#issuecomment-130340098), we decided:

> We're unable to find a code of conduct that seems to fit what we need and the project is still relatively small. Given this we're going to defer the issue to some future date.

Perhaps that time is now. Can you tell me why you want to add a code of conduct to ActiveInteraction?

**Comment by waldyr** [comment]
I saw Aaron's post about services (which is an awesome post) and I started felt like reading the code of ActiveInteraction. As I haven't noticed any COC in this project I thought it would be good to have one. And that's why I wanted to add one. Feel free to close this issue if it still not the time to add it or it still does not fit well. There's no hard feelings about it 😄 .

**Comment by AaronLasseigne** [comment]
I will say that the Contributor Covenant has improved since we first looked at it. I'd like to take some time to think about this and talk it over with Taylor. We want people to feel comfortable contributing to our project (PRs are great) but CoCs are pretty serious things and we'll want to make sure it fits with what we want.

Thanks for the PR and I'm glad you liked the post!

**Comment by tfausak** [comment]
After (a lot!) of thought and discussion, it has become apparent that our feelings haven't changed since the last time we discussed this. To wit:

> We're unable to find a code of conduct that seems to fit what we need and the project is still relatively small. Given this we're going to defer the issue to some future date.

And thank you for your interest in the project, @waldyr!

**Pull request closed without merging**
