### PR TITLE
Add a base option to integer filters

### LINKED ISSUE #386: Integer filter handles strings unexpectedly
Not sure if bug or feature:

When I use the `integer` filter and a string is passed in, the value is coerced into an integer using Ruby's Integer coercion.  However, we get situations like this:

```
2.0.0-p645 :002 > Integer("07")
 => 7
2.0.0-p645 :003 > Integer("08")
ArgumentError: invalid value for Integer(): "08"
```

This is quite unexpected. I would imagine either it always errors or always succeeds. I know this is Ruby and not really ActiveInteraction...but was wondering if we should continue to use `Integer(X)` for conversion.

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #386.

### CODE REVIEW

**Comment by tfausak** [comment]
@AaronLasseigne can you review this?

**Comment by ngan** [comment]
Thanks for the PR! Just a thought: I would imagine everyone out there would now have to add base 10 to their interactions...since it's 99% of the use case out there. I believe this is the same reason JavaScript made base 10 the default for `parseInt`.

**Comment by ngan** [comment]
Forgot my point: Should we default it to base 10?

**Comment by tfausak** [comment]
I would like to make `base: 10` the default, but that'd be a backwards-incompatible change.

**Comment by ngan** [comment]
I see, makes sense. Can we be sure to make the default 10 on the next "backwards-compability breaking" release?

**Comment by AaronLasseigne** [comment]
Code looks great. We need to add some docs on it to the README.

**Comment by ngan** [comment]
> We need to add some docs on it to the README.

Add README update in #391. Thanks! Let's :shipit:

**Pull request merged**
