### PR TITLE
Attach errors to invalid interaction exceptions

### LINKED ISSUE #273: Feature request: Populate symbolic errors in InvalidInteractionError
It would be great to fetch the symbolic error(s) from any InvalidInteractionError exception.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #273.

### CODE REVIEW

**Comment by AaronLasseigne** [comment]
I'm not sure about this.

**Comment by tfausak** [comment]
I'm of two minds about it. On one hand, it's an easy addition. On the other, you should use `.run` if you're going to analyze the errors. 

That being said, it might make sense to provide this anyway. Maybe there are situations where it's more appropriate to use exceptions for control flow.

**Comment by AaronLasseigne** [comment]
I'd like to see a better use case.

**Comment by tfausak** [comment]
I agree.

**Pull request closed without merging**
