### PR TITLE
Drop support for Ruby 1.9.3

### LINKED ISSUE #246: Drop support for 1.9.3
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

Official support for 1.9.3 stops on Feb 23 2014.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #246.

### CODE REVIEW

**Comment by AaronLasseigne** [comment]
Do we have any places that we could be using `%i`?

**Comment by tfausak** [comment]
Good call.

**Comment by tfausak** [comment]
The build is failing because JRuby isn't running in 2.x mode and Rubinius still needs the back ports for grouped inputs.

**Comment by tfausak** [comment]
If we drop support for MRI 1.9.3, it seems like we'll have to drop CI support for JRuby and Rubinius.

**Comment by AaronLasseigne** [comment]
Right. It's we should probably skip this for now.

**Pull request closed without merging**
