### PR TITLE
Do not translate error strings on :base when merging errors.

### LINKED ISSUE #349: merging existing base string errors fails
```rb
class I < ActiveInteraction::Base
  validate :v
  def execute; end
  def v; errors.add(:base, 'failed'); end
end

class E < ActiveInteraction::Base
  def execute; compose(I); end
end

> E.run.errors.messages
# => {:base=>["translation missing: en.active_interaction.errors.models.i.attributes.base.failed"]}
```

### PR DESCRIPTION
**Pull request by AaronLasseigne**
This only occurs when errors that are strings are added to `:base` and then composed into another interaction.

fixes #349

### CODE REVIEW

**Comment by AaronLasseigne** [comment]
@tfausak please take a look

**Comment by AaronLasseigne** [comment]
For some reason Rubocop is failing. I tried 2.2.4 locally and it worked fine. Glitch in the matrix?

**Comment by tfausak** [comment]
I think Travis is using RuboCop 0.36, which probably introduced a bunch of new cops.

**Comment by tfausak** [comment]
:shipit: 

I made a pull request (#351) for the RuboCop changes.

**Pull request merged**
