### PR TITLE
Add frozen string pragma

### LINKED ISSUE #335: Ruby 2.3 preparedness
With 2.3 around the corner we need to make sure the code works. Right now all tests pass in 2.3 (run locally) and I don't see anything that should cause us problems. We need to make sure 2.3 is added to our Travis CI runs when it becomes available.

Ruby 2.3 is introducing a pragma to make all strings immutable by default. The though is that by Ruby 3 this will be standard. It works by adding `# frozen_string_literal: true` to the top of the file. Then all strings created using single or double quotes are immutable. If you need a mutable string it will need to be created using `String.new`.

I would like to adopt the new pragma so that people using 2.3 can get the performance benefit and we're ready for Ruby 3 ahead of time. @tfausak thoughts?

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #335. 

Tested locally with Ruby 2.3.0-preview2. All of the tests pass.

### CODE REVIEW

**Comment by tfausak** [comment]
Raw benchmark results.

# Without pragma

```
Rehearsal ----------------------------------------------------------------------------------------
baseline                                               0.350000   0.000000   0.350000 (  0.347545)
array.cast([])                                         0.070000   0.000000   0.070000 (  0.070843)
boolean.cast(false)                                    0.000000   0.000000   0.000000 (  0.000876)
boolean.cast("0")                                      0.000000   0.000000   0.000000 (  0.001399)
boolean.cast("false")                                  0.010000   0.000000   0.010000 (  0.008608)
boolean.cast(true)                                     0.010000   0.000000   0.010000 (  0.003816)
boolean.cast("1")                                      0.000000   0.000000   0.000000 (  0.005089)
boolean.cast("true")                                   0.010000   0.000000   0.010000 (  0.011282)
date.cast(Mon, 01 Jan -4712)                           0.010000   0.000000   0.010000 (  0.003477)
date.cast("-4712-01-01")                               0.040000   0.000000   0.040000 (  0.045156)
date_time.cast(Mon, 01 Jan -4712 00:00:00 +0000)       0.010000   0.000000   0.010000 (  0.004416)
date_time.cast("-4712-01-01T00:00:00+00:00")           0.130000   0.000000   0.130000 (  0.136035)
decimal.cast(#<BigDecimal:7fb80b8c9928,'0.0',9(27)>)   0.010000   0.000000   0.010000 (  0.005341)
file.cast(#<File:benchmarks/filters.rb>)               0.000000   0.000000   0.000000 (  0.005937)
float.cast(0.0)                                        0.010000   0.000000   0.010000 (  0.001328)
float.cast("0.0")                                      0.000000   0.000000   0.000000 (  0.006389)
float.cast(0)                                          0.010000   0.000000   0.010000 (  0.005686)
hash.cast({})                                          0.020000   0.000000   0.020000 (  0.018301)
integer.cast(0)                                        0.000000   0.000000   0.000000 (  0.001392)
integer.cast("0")                                      0.000000   0.000000   0.000000 (  0.006313)
integer.cast(0.0)                                      0.010000   0.000000   0.010000 (  0.005507)
interface.cast(#<Object:0x007fb80b8c96f8>)             0.000000   0.000000   0.000000 (  0.002544)
object.cast(#<Object:0x007fb80b8c96a8>)                0.000000   0.000000   0.000000 (  0.001537)
string.cast("")                                        0.000000   0.000000   0.000000 (  0.001919)
symbol.cast(:"")                                       0.010000   0.000000   0.010000 (  0.000882)
symbol.cast("")                                        0.000000   0.000000   0.000000 (  0.001748)
time.cast(1969-12-31 18:00:00 -0600)                   0.020000   0.000000   0.020000 (  0.019735)
time.cast("1969-12-31 18:00:00 -0600")                 0.220000   0.000000   0.220000 (  0.222317)
time.cast(0)                                           0.010000   0.000000   0.010000 (  0.009298)
------------------------------------------------------------------------------- total: 0.960000sec

                                                           user     system      total        real
baseline                                               0.330000   0.000000   0.330000 (  0.332318)
array.cast([])                                         0.060000   0.000000   0.060000 (  0.061277)
boolean.cast(false)                                    0.000000   0.000000   0.000000 (  0.000891)
boolean.cast("0")                                      0.000000   0.000000   0.000000 (  0.001329)
boolean.cast("false")                                  0.010000   0.000000   0.010000 (  0.007105)
boolean.cast(true)                                     0.000000   0.000000   0.000000 (  0.002696)
boolean.cast("1")                                      0.000000   0.000000   0.000000 (  0.004531)
boolean.cast("true")                                   0.010000   0.000000   0.010000 (  0.009972)
date.cast(Mon, 01 Jan -4712)                           0.000000   0.000000   0.000000 (  0.002646)
date.cast("-4712-01-01")                               0.040000   0.000000   0.040000 (  0.037857)
date_time.cast(Mon, 01 Jan -4712 00:00:00 +0000)       0.000000   0.000000   0.000000 (  0.002632)
date_time.cast("-4712-01-01T00:00:00+00:00")           0.140000   0.000000   0.140000 (  0.136277)
decimal.cast(#<BigDecimal:7fb80b8c9928,'0.0',9(27)>)   0.000000   0.000000   0.000000 (  0.004083)
file.cast(#<File:benchmarks/filters.rb>)               0.000000   0.000000   0.000000 (  0.003151)
float.cast(0.0)                                        0.000000   0.000000   0.000000 (  0.001351)
float.cast("0.0")                                      0.000000   0.000000   0.000000 (  0.004568)
float.cast(0)                                          0.000000   0.000000   0.000000 (  0.003968)
hash.cast({})                                          0.010000   0.000000   0.010000 (  0.014121)
integer.cast(0)                                        0.000000   0.000000   0.000000 (  0.001316)
integer.cast("0")                                      0.010000   0.000000   0.010000 (  0.005010)
integer.cast(0.0)                                      0.010000   0.000000   0.010000 (  0.004449)
interface.cast(#<Object:0x007fb80b8c96f8>)             0.000000   0.000000   0.000000 (  0.002119)
object.cast(#<Object:0x007fb80b8c96a8>)                0.000000   0.000000   0.000000 (  0.001528)
string.cast("")                                        0.000000   0.000000   0.000000 (  0.001793)
symbol.cast(:"")                                       0.000000   0.000000   0.000000 (  0.000915)
symbol.cast("")                                        0.000000   0.000000   0.000000 (  0.001778)
time.cast(1969-12-31 18:00:00 -0600)                   0.010000   0.000000   0.010000 (  0.010914)
time.cast("1969-12-31 18:00:00 -0600")                 0.210000   0.000000   0.210000 (  0.216155)
time.cast(0)                                           0.010000   0.000000   0.010000 (  0.006659)
```

# With pragma

```
Rehearsal ----------------------------------------------------------------------------------------
baseline                                               0.340000   0.000000   0.340000 (  0.346002)
array.cast([])                                         0.070000   0.000000   0.070000 (  0.067100)
boolean.cast(false)                                    0.000000   0.000000   0.000000 (  0.000882)
boolean.cast("0")                                      0.000000   0.000000   0.000000 (  0.001298)
boolean.cast("false")                                  0.010000   0.000000   0.010000 (  0.008528)
boolean.cast(true)                                     0.000000   0.000000   0.000000 (  0.003169)
boolean.cast("1")                                      0.010000   0.000000   0.010000 (  0.004988)
boolean.cast("true")                                   0.010000   0.000000   0.010000 (  0.011551)
date.cast(Mon, 01 Jan -4712)                           0.000000   0.000000   0.000000 (  0.003519)
date.cast("-4712-01-01")                               0.050000   0.000000   0.050000 (  0.046200)
date_time.cast(Mon, 01 Jan -4712 00:00:00 +0000)       0.000000   0.000000   0.000000 (  0.004371)
date_time.cast("-4712-01-01T00:00:00+00:00")           0.150000   0.000000   0.150000 (  0.143409)
decimal.cast(#<BigDecimal:7fd6f2fd0630,'0.0',9(27)>)   0.000000   0.000000   0.000000 (  0.004994)
file.cast(#<File:benchmarks/filters.rb>)               0.010000   0.000000   0.010000 (  0.005719)
float.cast(0.0)                                        0.000000   0.000000   0.000000 (  0.001325)
float.cast("0.0")                                      0.000000   0.000000   0.000000 (  0.005404)
float.cast(0)                                          0.010000   0.000000   0.010000 (  0.004752)
hash.cast({})                                          0.020000   0.000000   0.020000 (  0.017149)
integer.cast(0)                                        0.000000   0.000000   0.000000 (  0.001336)
integer.cast("0")                                      0.000000   0.000000   0.000000 (  0.005799)
integer.cast(0.0)                                      0.010000   0.000000   0.010000 (  0.005256)
interface.cast(#<Object:0x007fd6f2fd0360>)             0.000000   0.000000   0.000000 (  0.002465)
object.cast(#<Object:0x007fd6f2fd0310>)                0.000000   0.000000   0.000000 (  0.001532)
string.cast("")                                        0.000000   0.000000   0.000000 (  0.001875)
symbol.cast(:"")                                       0.000000   0.000000   0.000000 (  0.000872)
symbol.cast("")                                        0.010000   0.000000   0.010000 (  0.001741)
time.cast(1969-12-31 18:00:00 -0600)                   0.010000   0.000000   0.010000 (  0.017472)
time.cast("1969-12-31 18:00:00 -0600")                 0.220000   0.000000   0.220000 (  0.219048)
time.cast(0)                                           0.010000   0.000000   0.010000 (  0.009174)
------------------------------------------------------------------------------- total: 0.940000sec

                                                           user     system      total        real
baseline                                               0.330000   0.000000   0.330000 (  0.328084)
array.cast([])                                         0.060000   0.000000   0.060000 (  0.059688)
boolean.cast(false)                                    0.000000   0.000000   0.000000 (  0.000944)
boolean.cast("0")                                      0.000000   0.000000   0.000000 (  0.001299)
boolean.cast("false")                                  0.010000   0.000000   0.010000 (  0.007424)
boolean.cast(true)                                     0.000000   0.000000   0.000000 (  0.002653)
boolean.cast("1")                                      0.000000   0.000000   0.000000 (  0.004463)
boolean.cast("true")                                   0.010000   0.000000   0.010000 (  0.010398)
date.cast(Mon, 01 Jan -4712)                           0.000000   0.000000   0.000000 (  0.002642)
date.cast("-4712-01-01")                               0.030000   0.000000   0.030000 (  0.038681)
date_time.cast(Mon, 01 Jan -4712 00:00:00 +0000)       0.000000   0.000000   0.000000 (  0.002627)
date_time.cast("-4712-01-01T00:00:00+00:00")           0.120000   0.000000   0.120000 (  0.126175)
decimal.cast(#<BigDecimal:7fd6f2fd0630,'0.0',9(27)>)   0.010000   0.000000   0.010000 (  0.004213)
file.cast(#<File:benchmarks/filters.rb>)               0.010000   0.000000   0.010000 (  0.003023)
float.cast(0.0)                                        0.000000   0.000000   0.000000 (  0.001312)
float.cast("0.0")                                      0.000000   0.000000   0.000000 (  0.004752)
float.cast(0)                                          0.000000   0.000000   0.000000 (  0.004010)
hash.cast({})                                          0.010000   0.000000   0.010000 (  0.015030)
integer.cast(0)                                        0.000000   0.000000   0.000000 (  0.001321)
integer.cast("0")                                      0.000000   0.000000   0.000000 (  0.004835)
integer.cast(0.0)                                      0.000000   0.000000   0.000000 (  0.004457)
interface.cast(#<Object:0x007fd6f2fd0360>)             0.000000   0.000000   0.000000 (  0.002089)
object.cast(#<Object:0x007fd6f2fd0310>)                0.000000   0.000000   0.000000 (  0.001517)
string.cast("")                                        0.000000   0.000000   0.000000 (  0.001784)
symbol.cast(:"")                                       0.000000   0.000000   0.000000 (  0.000985)
symbol.cast("")                                        0.010000   0.000000   0.010000 (  0.001779)
time.cast(1969-12-31 18:00:00 -0600)                   0.010000   0.000000   0.010000 (  0.010996)
time.cast("1969-12-31 18:00:00 -0600")                 0.210000   0.000000   0.210000 (  0.215601)
time.cast(0)                                           0.010000   0.000000   0.010000 (  0.006602)
```

**Comment by tfausak** [comment]
Since that data is hard to grok, here is a graph of it.

frozen

The results are close. I think I'll run another benchmark using IPS to get a better idea of what's going on.

**Comment by tfausak** [comment]
With the new benchmark, most things are faster by about 2%.

untitled

thawed | frozen | delta
--- | --- | ---
24.392 | 24.828 | 0.436
44.547 | 44.698 | 0.151
42.281 | 42.968 | 0.687
42.545 | 43.067 | 0.522
40.988 | 41.874 | 0.886
42.507 | 42.571 | 0.064
43.666 | 44.398 | 0.732
34.002 | 34.798 | 0.796
43.789 | 44.160 | 0.371
43.114 | 42.774 | -0.340
43.504 | 44.270 | 0.766
43.444 | 43.700 | 0.256
44.320 | 44.749 | 0.429
36.616 | 37.079 | 0.463

# Without pragma

```
              lambda      2.066M (± 5.7%) i/s -     10.324M
               array     24.392k (± 2.6%) i/s -    123.180k
             boolean     44.547k (± 1.9%) i/s -    223.320k
                date     42.281k (± 2.4%) i/s -    213.256k
           date_time     42.545k (± 2.4%) i/s -    214.140k
             decimal     40.988k (± 2.7%) i/s -    206.382k
                file     42.507k (± 2.1%) i/s -    215.100k
               float     43.666k (± 2.1%) i/s -    221.220k
                hash     34.002k (± 1.8%) i/s -    171.390k
             integer     43.789k (± 2.2%) i/s -    220.620k
           interface     43.114k (± 2.2%) i/s -    216.977k
              object     43.504k (± 2.0%) i/s -    217.474k
              string     43.444k (± 2.2%) i/s -    219.720k
              symbol     44.320k (± 2.5%) i/s -    222.253k
                time     36.616k (± 2.8%) i/s -    184.440k
```

# With pragma

```
              lambda      2.072M (± 4.8%) i/s -     10.334M
               array     24.828k (± 1.7%) i/s -    124.410k
             boolean     44.698k (± 2.1%) i/s -    223.474k
                date     42.968k (± 1.9%) i/s -    216.630k
           date_time     43.067k (± 1.7%) i/s -    218.772k
             decimal     41.874k (± 2.0%) i/s -    211.294k
                file     42.571k (± 1.6%) i/s -    216.398k
               float     44.398k (± 2.8%) i/s -    223.996k
                hash     34.798k (± 1.6%) i/s -    175.674k
             integer     44.160k (± 2.2%) i/s -    221.966k
           interface     42.774k (± 3.1%) i/s -    214.704k
              object     44.270k (± 2.2%) i/s -    221.730k
              string     43.700k (± 2.3%) i/s -    220.516k
              symbol     44.749k (± 2.2%) i/s -    223.725k
                time     37.079k (± 2.0%) i/s -    187.746k
```

**Comment by tfausak** [comment]
What do you think, @AaronLasseigne? I'm not too impressed with the performance increase, but faster is faster

**Comment by AaronLasseigne** [comment]
Faster is indeed faster and it's also makes sure we're looking forward toward what's coming.

**Comment by tfausak** [comment]
How do you feel about the new benchmark? I think it's a better test of actually using ActiveInteraction.

**Comment by AaronLasseigne** [comment]
The new one as in [this](https://github.com/orgsync/active_interaction/pull/336#issuecomment-165531847) one?

**Comment by AaronLasseigne** [comment]
Oh, wait, you mean the benchmark file. I like IPS and I think it's a good choice. What makes you think it's a better test?

**Comment by tfausak** [comment]
I like that it actually runs an interaction instead of just passing a value through a filter.

**Comment by AaronLasseigne** [comment]
I think that's good.

**Pull request merged**
