### PR TITLE
switch internal only error to a throw/catch

### PR DESCRIPTION
**Pull request by AaronLasseigne**
There's no need for a full on error object here. Ruby has throw/catch to handle this and it help distinguish errors that might reach the end user from what is otherwise an internal signal.

### CODE REVIEW

**Comment by AaronLasseigne** [comment]
Also, throw/catch is faster than fail/rescue.

**Comment by tfausak** [comment]
I'm not opposed to this, but can we show that it's faster with a benchmark?

**Comment by AaronLasseigne** [comment]
Run with Ruby 2.2.3:

```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  x.report('Catch/Throw') do
    catch(:benchmarking) do
      throw(:benchmarking)
    end
  end

  x.report('Fail/Rescue') do
    begin
      fail StandardError
    rescue StandardError
      # do nothing
    end
  end

  x.compare!
end
```

```
Calculating -------------------------------------
         Catch/Throw    73.753k i/100ms
         Fail/Rescue    33.262k i/100ms
-------------------------------------------------
         Catch/Throw      1.990M (± 8.6%) i/s -      9.883M
         Fail/Rescue    518.015k (± 6.6%) i/s -      2.594M

Comparison:
         Catch/Throw:  1990106.8 i/s
         Fail/Rescue:   518015.2 i/s - 3.84x slower
```

**Comment by tfausak** [comment]
:shipit:

**Comment by AaronLasseigne** [comment]
Thanks for the review.

**Pull request merged**
