### PR TITLE
Copy symbolic errors when composing

### LINKED ISSUE #87: compose does not copy symbolic errors
When using `compose` with an interaction that uses `add_sym` to create symbolic errors, the `compose` method doesn't pass these symbolic errors along to the outcome.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #87.

### CODE REVIEW

**Comment by tfausak** [comment]
Another one for you to review, @AaronLasseigne. This suffers from the same problems mentioned in https://github.com/orgsync/active_interaction/pull/194#issuecomment-43345208, but I think the tradeoffs are worth it. 

I think #245 could provide a better long-term solution for this. I don't want to let perfect be the enemy of good, though.

**Comment by AaronLasseigne** [comment]
It looks good and what we currently do is (as you pointed out) not very good. I think we just need to mention some of these sharp edges in the docs.

**Comment by tfausak** [comment]
Should I add that to the "Errors" section or the "Composition" section?

**Comment by AaronLasseigne** [comment]
Probably the "Errors" section and then link to it from the "Composition" section. Does that sound reasonable?

**Comment by tfausak** [comment]
:+1:

**Comment by tfausak** [comment]
I updated the documentation.

**Comment by AaronLasseigne** [comment]
:shipit:

**Comment by tfausak** [comment]
This is a breaking change, so it'll need to be merged into a branch for v3.0.0.

**Comment by AaronLasseigne** [comment]
True.

**Pull request merged**
