### PR TITLE
Warn when redefining a filter

### PR DESCRIPTION
**Pull request by tfausak**
This pull request makes it so that you get a warning when you redefine a filter. Issue #308 brought the need for this to my attention. 

Here is an example of the warning:

``` rb
class Example < ActiveInteraction::Base
  boolean :x, :x
end
# WARNING: Redefining Example#x filter!
```

### CODE REVIEW

**Comment by tfausak** [comment]
I am open to better wording. As is, it gives you enough information to figure out what's going on. But we may want to include more, like filter types.

**Comment by tfausak** [comment]
The build failed because RuboCop thinks `ActiveInteraction::Base` has too many lines. We can either increase the maximum class length or figure out how to break it up.

**Comment by AaronLasseigne** [comment]
Is there any case where you might intentionally redefine a filter? I can't really think of one. Maybe on some kind of conditional filter import? Should we just raise an error instead?

Also, I don't think it needs to be so excited (i.e. we can drop the "!").

**Comment by tfausak** [comment]
I can get behind raising an error instead of a warning. But that would be a major change to our API, right? And if we did raise an error, would we want to allow users to ignore it?

There has never been an instance where I wanted to redefine a filter. I do sometimes want to modify them, but I use `.filters` for that.

**Comment by AaronLasseigne** [comment]
Maybe it's best that we just warn. There might be some situation we're not considering where it makes sense.

BTW, the code looks :+1:

**Comment by MustafaZain** [comment]
@tfausak What if I have something like this

```
class Base < ActiveInteraction::Base
    object :user
    object :address
end
```

and another class that will inherit from `Base` and want the `address` for it to be optional for the other class

``` 
class ChildClass < Base
    object :address, default: nil
end
```

I got a warning `WARNING: Redefining` while this is intended 🤔

**Comment by matiasasis** [comment]
Leaving this as it may be useful for some:

We encountered the same issue, using inheritance and getting the warning which can be annoying. 

And the solution we found was to locally override the warn method.

if you have your own `ApplicationInteraction::Base` this could do the trick:

```
  class << self
    def warn(*args)
      # Do something, or not...
    end
  end
```

**Pull request merged**
