### PR TITLE
Accept associations as inputs for array filters

### LINKED ISSUE #301: Validation array with model
Using 1.6, I'm not able to validate
```
array :contracts
```
or 
```
array :contracts do
   model
end
```
or
```
array :contracts do
   model class: Contract
end
```

### PR DESCRIPTION
**Pull request by tfausak**
This pull request will fix #301.

### CODE REVIEW

**Comment by tfausak** [comment]
The specs are failing because the specs are using `eql` instead of `eq`. We started doing that in e454f1ee2c1ce1743c73fed275a100db1446816d. Collection proxies aren't `eql` to arrays, which is the root cause of #301. 

Since we didn't really switch to `eql` for any particular reason, I think I'll change them over.

**Comment by tfausak** [comment]
Hmm, now the build is failing because `sqlite3` won't build on JRuby.

**Comment by AaronLasseigne** [comment]
Can we just mock instead?

**Comment by tfausak** [comment]
We can! That worked well. Can you review these changes?

**Comment by AaronLasseigne** [comment]
:+1:

**Pull request merged**
